server:
  mode: "debug"
  ip: "192.168.43.219"
  #  mode: "release"
  #  ip: "192.168.70.105"
  port: 8080
snowflake:
  start_at: "2023-02-01"
  machines: 1
logger:
  filename: "douyin.log"
  layout: "[2006-01-02 15:04:05]"
  max_size: 200
  max_age: 30
  max_backups: 7
ffmpeg:
  ffmpeg_path: "C:\\Environment\\Go\\bin\\ffmpeg.exe"
  public_path: "C:\\Users\\18446\\GolandProjects\\project\\douyin\\public"
  public_pic_path: "C:\\Users\\18446\\GolandProjects\\project\\douyin\\public\\pic"
mysql:
  host: "127.0.0.1"
  port: 3306
  dbname: "douyin"
  username: "root"
  password: "541688"
  max_idles_conns: 50
  max_opens_conns: 200
redis:
  addr: "cczj:6379"
  password: ""
  user_db: 1
  relation_db: 2
  video_db: 3
  favor_db: 4
  comment_db: 5
  pool_size: 100
mongo:
  addr: "cczj:27017"
  max_pools: 50
  min_pools: 20
  max_opens_conns: 200